// import slugify from '../utils/slugify'

export default {
  title: "Authors",
  name: 'authors',
  type: "document",
  fields: [
    {
      title: "Name",
      name: "name",
      type: "string",
      validation: Rule => Rule.required()
    },
    // {
    //   name: 'slug',
    //   type: 'slug',
    //   title: 'Slug',
    //   description: 'This is required for page routing and can be auto-generated by pressing "generate"',
    //   options: {
    //     source: (doc) => {
    //       let titleSlug = ''
    //       let campaignSlug = ''
    //       if (doc.title) {
    //         titleSlug = `${doc.title}`
    //       } else {
    //         titleSlug = ''
    //       }

    //       if (doc.campaignTitle) {
    //         campaignSlug = `-${doc.campaignTitle}`
    //       } else {
    //         campaignSlug = ''
    //       }

    //       return `${titleSlug}${campaignSlug}`;
    //     },
    //     maxLength: 96,
    //     slugify: (input) => slugify(`${input}`)
    //   },
    //   validation: Rule => Rule.required()
    // }
  ],
  preview: {
    select: {
      title: 'name'
    }
  }
}