import slugify from '../utils/slugify'

export default {
  title: "Case Studies",
  name: 'caseStudies',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this release",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Hero Image",
      description: "The name of this release",
      name: "heroImage",
      type: "defaultImage",
      validation: Rule => Rule.required()
    },
    {
      title: "Partner Name",
      description: "Name of the partner for this success story, eg: 'Puzzle Dream'",
      name: "partnerName",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Project Name",
      description: "Name of the project for this success story, eg: 'Cube Blast Journey'",
      name: "projectName",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Publish Date",
      description: "Press the button to the right to pick a date.",
      name: "publishDate",
      type: "date",
      options: {
        dateFormat: "MMMM Do YYYY",
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'Content Sections',
      name: 'contentSections',
      description: 'The modular content sections for this article',
      type: 'array',
      of: [
        {
          title: 'Section',
          type: 'object',
          name: 'section',
          fields: [
            {
              title: 'Title',
              name: 'title',
              type: 'string',
            },
            {
              title: 'Content Blocks',
              name: 'contentBlocks',
              description: 'The modular content blocks for this article',
              type: 'array',
              of: [
                {type: 'textBlock', title: 'Text'},
                {type: 'modularImageBlock', title: 'Image'},
                {type: 'modularQuoteBlock', title: 'Quote'},
              ],
            }
          ],
        }
      ],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let projectSlug = ''
          let partnerSlug = ''
          if (doc.projectName) {
            projectSlug = `${doc.projectName}`
          } else {
            projectSlug = ''
          }

          if (doc.partnerName) {
            partnerSlug = `-${doc.partnerName}`
          } else {
            partnerSlug = ''
          }

          return `${projectSlug}${partnerSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'publishDate',
      media: 'heroImage'
    }
  }
}