// import slugify from '../utils/slugify'

export default {
  title: "Games Library",
  name: 'gamesLibrary',
  type: "document",
  fields: [
    {
      title: "Title",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Partner Name",
      description: "Name of the partner for this game if it had one, eg: 'Funcell'",
      name: "partnerName",
      type: "string"
    },
    {
      title: "Google Play Store Link",
      name: "googlePlayStoreLink",
      type: "url"
    },
    {
      title: "App Store Link",
      name: "appStoreLink",
      type: "url"
    },
    // {
    //   name: 'slug',
    //   type: 'slug',
    //   title: 'Slug',
    //   description: 'This is required for page routing and can be auto-generated by pressing "generate"',
    //   options: {
    //     source: (doc) => {
    //       let titleSlug = ''
    //       let campaignSlug = ''
    //       if (doc.title) {
    //         titleSlug = `${doc.title}`
    //       } else {
    //         titleSlug = ''
    //       }

    //       if (doc.campaignTitle) {
    //         campaignSlug = `-${doc.campaignTitle}`
    //       } else {
    //         campaignSlug = ''
    //       }

    //       return `${titleSlug}${campaignSlug}`;
    //     },
    //     maxLength: 96,
    //     slugify: (input) => slugify(`${input}`)
    //   },
    //   validation: Rule => Rule.required()
    // }
  ],
  preview: {
    select: {
      title: 'title'
    }
  }
}