import slugify from '../utils/slugify'

export default {
  title: "Marketing",
  name: 'marketingPages',
  type: "document",
  fields: [
    {
      title: "Title",
      description: "The name of this page",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: 'Content Blocks',
      name: 'contentBlocks',
      description: 'The modular content blocks for this article',
      type: 'array',
      of: [
        {type: 'modularMarketingHeroBlock', title: 'Hero Block'},
        {type: 'modularMarketingTextImageSplitBlock', title: 'Text / Image Split Block'},
        {type: 'modularMarketingTextOverImageBlock', title: 'Text Over Image Block'},
        {type: 'modularMarketingCondensedCtaBlock', title: 'Condensed CTA Block'},
        {type: 'modularMarketingLongIconListBlock', title: 'Long Icon List Block'},
        {type: 'modularMarketingMultipleCtaBlock', title: 'Multiple CTA Block'},
        {type: 'modularMarketingTextIconBlock', title: 'Text + Icon Block'},
        {type: 'modularMarketingIconBlock', title: 'Icon Block'},
        {type: 'modularMarketingHubspotFormBlock', title: 'Hubspot Form Block'},
        {type: 'modularMarketingCareersBlock', title: 'Careers Block'},
        {type: 'modularMarketingCaseStudiesBlock', title: 'Case Studies Block'},
        {type: 'modularMarketingNewsFeedBlock', title: 'News Feed Block'},
        {type: 'modularMarketingPeopleCarouselBlock', title: 'People Carousel Block'},
        {type: 'modularMarketingGamesFeedBlock', title: 'Games Feed Block'},
        {type: 'modularMarketingStatListBlock', title: 'Stat List Block'},
        {type: 'modularMarketingImageCarouselBlock', title: 'Image Carousel Block'},
        {type: 'embedBlock', title: 'Embed'},
      ],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
    }
  }
}